### ISSUE TITLE
Compilation error 7724d25

### ISSUE THREAD

**Issue by ejovo13** [alsoc/fmdt#8]
When building fmdt on the develop branch  with g++ 12.2.1 and the following options
![image](https://user-images.githubusercontent.com/40283612/216769254-7f326a4f-15e9-4c0d-8ebd-7bfd4dbd36e0.png)
I get the following compilation error
![image](https://user-images.githubusercontent.com/40283612/216769312-d956aa94-42da-429a-aa35-d4ae91fee786.png)
Inspecting `ffmpeg_options` reveals that the fields `start_number` and `vframes` are non-existent.
![image](https://user-images.githubusercontent.com/40283612/216769454-2c69b8c8-706d-43e7-a313-3a7dcff83520.png)

**Comment by kouchy** [comment]
Hi @ejovo13,
I think you did not update the sub-modules.
Try to do : `git submodule update --recursive`, it should update ffmpeg-io correctly.

**Comment by ejovo13** [comment]
Thank you, that worked. I had called `git submodule update --init --recursive` and some things got updated, but I guess it was obviously the wrong command. I admit I'm not completely familiar with the `submodule` syntax and all of the options.
